### get administradores
GET http://localhost:8080/administradores
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6OCwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTgzLCJjb250cmFzZW5pYSI6IiQyYSQxMCRtSU9zNTdReFFneExvTVY1SnVabFh1eWR6STRXc3pnM21DaGxwMW1wL3pwbGtUMDNnWnN6SyIsImVzX2VzcGVjaWFsIjp0cnVlLCJpYXQiOjE3NzY3Nzk0MDEsImV4cCI6MTc3Njc5MDIwMX0.qXngQOMJQmbsxAfvy2uewdgxr5WzBbCYDYLhmi07dFg"

### get administrador
GET http://localhost:8080/administradores/1
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RfYWRtaW5pc3RyYWRvciI6Niwibm9tYnJlIjoiSnVhbiIsImFwZWxsaWRvIjoiTG9wZXoiLCJkbmkiOjM0MzQ0NTMsImZlY2hhX2luaV9jb250cmF0byI6IjIwMjQtMDktMDlUMDA6MDA6MDAuMDAwWiIsImZlY2hhX2Zpbl9jb250cmF0byI6bnVsbCwiY29udHJhc2VuaWEiOiIkMmEkMTAkWWJwaTVUNTBMc3VUWUNMUjVrQ2dLT0Rvek9RTjdzSkRuY0hYVlMueThoY3JibTVqRlVxWmEiLCJwZXJtaXNzaW9ucyI6WyIqIl0sImlhdCI6MTc0MTIzMDk2NiwiZXhwIjoxNzQxMjQxNzY2fQ.S3Ef9Grlpdu1wDL7IR5PEREVI71jRKricLRPJ8-zgek"

### log in de administrador
POST http://localhost:8080/administradores/logIn
Content-Type: application/json

{
    "cod_administrador": 8,
    "contrasenia": "123r"
}

### POST an admin
POST http://localhost:8080/administradores/
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Lopez",
    "dni": 34344583,
    "contrasenia": "123r",
    "es_especial": true
}






